on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  kotlin:
    name: Kotlin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: Kotlin Test
        working-directory: drive-kotlin
        run: mvn --batch-mode test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: Test
        run: go test ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: golangci-lint
        run: golangci-lint run
      - name: go-check-sumtype
        run: go-check-sumtype ./...
